USE codeup_test_db;

DROP TABLE IF EXISTS albums;

 CREATE TABLE IF NOT EXISTS albums(
 id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
 artist VARCHAR(100) NOT NULL,
 name VARCHAR(100) NOT NULL,
 release_date INT,
 sales FLOAT,
 genre CHAR(100)
 );